Default: &defaults
  user: jack
  password: "1234"
  host: localhost
  database: webmap
  connections: 10

Development:
  <<: *defaults

Testing:
  database: Test_test
  <<: *defaults

Staging:
  database: Test_staging
  connections: 100
  <<: *defaults

Production:
  database: Test_production
  connections: 100
  host: localhost
  <<: *defaults
