Default: &defaults
  database: webmap.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: webmap_test.sqlite3
  <<: *defaults

Staging:
  database: webmap_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: webmap_production.sqlite3
  poolsize: 100
  <<: *defaults
